model_version: "1.5"
model_ckpt: null
model_name: dreamlike-art/dreamlike-photoreal-2.0
prompt: photo of a dog running on grassland, masterpiece, best quality, fine details
negative_prompt: lowres, bad anatomy, bad hands, cropped, worst quality
liked: []
disliked: []
n_images: 4
denoising_steps: 20
guidance_scale: 7
seed: 37
feedback:
  start: 0.33
  end: 0.66
  min_weight: 0.05
  max_weight: 0.8
  neg_scale: 0.5
